version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" 
    depends_on:
      - mongodb
    networks:
      - finance-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - finance-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - finance-net

volumes:
  mongodb-data:

networks:
  finance-net:
    driver: bridge
